export const DATA_SOURCE_ACTION = 'DATA_SOURCE_ACTION';
export const DATA_SOURCE_ACTION_SUCCESS = 'DATA_SOURCE_ACTION_SUCCESS';
export const DATA_SOURCE_ACTION_FAILURE = 'DATA_SOURCE_ACTION_FAILURE';
export const DATA_SOURCE_ACTION_LIST = 'DATA_SOURCE_ACTION_LIST';
export const OPEN_API_URL = 'OPEN_API_URL';