export const GETTING_START_ACTION = 'GETTING_START_ACTION';
export const GETTING_START_ACTION_SUCCESS = 'GETTING_START_ACTION_SUCCESS';
export const GETTING_START_ACTION_FAILURE = 'GETTING_START_ACTION_FAILURE';

export const LIST_CONNECTION_ACTION = 'LIST_CONNECTION_ACTION';
export const LIST_CONNECTION_ACTION_SUCCESS = 'LIST_CONNECTION_ACTION_SUCCESS';
export const LIST_CONNECTION_ACTION_FAILURE = 'LIST_CONNECTION_ACTION_FAILURE';

export const VERIFICATION_TEMPLATE_SUCCESS = "VERIFICATION_TEMPLATE_SUCCESS";

export const CREATE_VERIFICATION_ACTION = "CREATE_VERIFICATION_ACTION";
export const CREATE_VERIFICATION_ACTION_SUCCESS = "CREATE_VERIFICATION_ACTION_SUCCESS";
export const CREATE_VERIFICATION_ACTION_FAILURE = "CREATE_VERIFICATION_ACTION_FAILURE";

export const READ_VERIFICATION_ACTION = "READ_VERIFICATION_ACTION";

export const UPDATE_DATA_SOURCE = "UPDATE_DATA_SOURCE";
export const UPDATE_DATA_SOURCE_SUCCESS = "UPDATE_DATA_SOURCE_SUCCESS";
export const UPDATE_DATA_SOURCE_FAILURE = "UPDATE_DATA_SOURCE_FAILURE";