export const GETTING_START_ACTION = 'GETTING_START_ACTION';
export const GETTING_START_ACTION_SUCCESS = 'GETTING_START_ACTION_SUCCESS';
export const GETTING_START_ACTION_FAILURE = 'GETTING_START_ACTION_FAILURE';