export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const LOGIN_ACTION_FAILURE = 'LOGIN_ACTION_FAILURE';

export const ADMIN_ACTION = 'ADMIN_ACTION';
export const ADMIN_ACTION_SUCCESS = 'ADMIN_ACTION_SUCCESS';
export const ADMIN_ACTION_FAILURE = 'ADMIN_ACTION_FAILURE';